// Embed kardashev-core (wasm32) into the site as base64 (Unibit-Web ADR-0003).
//   cd core && cargo build --release --target wasm32-unknown-unknown --lib
//   node --experimental-strip-types scripts/embed-core.ts
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const wasm = readFileSync(new URL("../core/target/wasm32-unknown-unknown/release/kardashev_core.wasm", import.meta.url));
const commit = execSync("git log -1 --format=%h --abbrev=12 -- core").toString().trim();
const dirty = execSync("git status --porcelain -- core").toString().trim() !== "";
writeFileSync(
  new URL("../src/lib/kardashev-core.gen.ts", import.meta.url),
  `// GENERATED by scripts/embed-core.ts from core/ (kardashev-core) at ${commit}${dirty ? " (DIRTY)" : ""}. Do not edit.\n` +
    `// ${wasm.length} bytes of wasm32: the core the golden gate holds bit-identical to the TypeScript it replaced.\n` +
    `export const KARDASHEV_CORE_COMMIT = "${commit}";\n` +
    `export const KARDASHEV_CORE_WASM_BASE64 =\n  "${wasm.toString("base64")}";\n`,
);
console.log(`embedded ${wasm.length} bytes of kardashev-core at ${commit}${dirty ? " (dirty)" : ""}`);
