/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AhoraRouteImport } from './routes/ahora'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as BiologiaRouteImport } from './routes/biologia'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as EnergiaRouteImport } from './routes/energia'
import { Route as FlotaRouteImport } from './routes/flota'
import { Route as GridRouteImport } from './routes/grid'
import { Route as IaRouteImport } from './routes/ia'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as QuantumRouteImport } from './routes/quantum'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SaludRouteImport } from './routes/salud'
import { Route as SectorRouteImport } from './routes/sector'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as StackRouteImport } from './routes/stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AhoraRoute = AhoraRouteImport.update({
  id: '/ahora',
  path: '/ahora',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const BiologiaRoute = BiologiaRouteImport.update({
  id: '/biologia',
  path: '/biologia',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaRoute = EnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => rootRouteImport,
} as any)
const FlotaRoute = FlotaRouteImport.update({
  id: '/flota',
  path: '/flota',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumRoute = QuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SaludRoute = SaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorRoute = SectorRouteImport.update({
  id: '/sector',
  path: '/sector',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ahora': typeof AhoraRoute
  '/bench': typeof BenchRoute
  '/biologia': typeof BiologiaRoute
  '/doctrine': typeof DoctrineRoute
  '/energia': typeof EnergiaRoute
  '/flota': typeof FlotaRoute
  '/grid': typeof GridRoute
  '/ia': typeof IaRoute
  '/plan': typeof PlanRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/roadmap': typeof RoadmapRoute
  '/salud': typeof SaludRoute
  '/sector': typeof SectorRoute
  '/space': typeof SpaceRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ahora': typeof AhoraRoute
  '/bench': typeof BenchRoute
  '/biologia': typeof BiologiaRoute
  '/doctrine': typeof DoctrineRoute
  '/energia': typeof EnergiaRoute
  '/flota': typeof FlotaRoute
  '/grid': typeof GridRoute
  '/ia': typeof IaRoute
  '/plan': typeof PlanRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/roadmap': typeof RoadmapRoute
  '/salud': typeof SaludRoute
  '/sector': typeof SectorRoute
  '/space': typeof SpaceRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ahora': typeof AhoraRoute
  '/bench': typeof BenchRoute
  '/biologia': typeof BiologiaRoute
  '/doctrine': typeof DoctrineRoute
  '/energia': typeof EnergiaRoute
  '/flota': typeof FlotaRoute
  '/grid': typeof GridRoute
  '/ia': typeof IaRoute
  '/plan': typeof PlanRoute
  '/quantum': typeof QuantumRoute
  '/research': typeof ResearchRoute
  '/roadmap': typeof RoadmapRoute
  '/salud': typeof SaludRoute
  '/sector': typeof SectorRoute
  '/space': typeof SpaceRoute
  '/stack': typeof StackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ahora'
    | '/bench'
    | '/biologia'
    | '/doctrine'
    | '/energia'
    | '/flota'
    | '/grid'
    | '/ia'
    | '/plan'
    | '/quantum'
    | '/research'
    | '/roadmap'
    | '/salud'
    | '/sector'
    | '/space'
    | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ahora'
    | '/bench'
    | '/biologia'
    | '/doctrine'
    | '/energia'
    | '/flota'
    | '/grid'
    | '/ia'
    | '/plan'
    | '/quantum'
    | '/research'
    | '/roadmap'
    | '/salud'
    | '/sector'
    | '/space'
    | '/stack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ahora'
    | '/bench'
    | '/biologia'
    | '/doctrine'
    | '/energia'
    | '/flota'
    | '/grid'
    | '/ia'
    | '/plan'
    | '/quantum'
    | '/research'
    | '/roadmap'
    | '/salud'
    | '/sector'
    | '/space'
    | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AhoraRoute: typeof AhoraRoute
  BenchRoute: typeof BenchRoute
  BiologiaRoute: typeof BiologiaRoute
  DoctrineRoute: typeof DoctrineRoute
  EnergiaRoute: typeof EnergiaRoute
  FlotaRoute: typeof FlotaRoute
  GridRoute: typeof GridRoute
  IaRoute: typeof IaRoute
  PlanRoute: typeof PlanRoute
  QuantumRoute: typeof QuantumRoute
  ResearchRoute: typeof ResearchRoute
  RoadmapRoute: typeof RoadmapRoute
  SaludRoute: typeof SaludRoute
  SectorRoute: typeof SectorRoute
  SpaceRoute: typeof SpaceRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ahora': {
      id: '/ahora'
      path: '/ahora'
      fullPath: '/ahora'
      preLoaderRoute: typeof AhoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biologia': {
      id: '/biologia'
      path: '/biologia'
      fullPath: '/biologia'
      preLoaderRoute: typeof BiologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia': {
      id: '/energia'
      path: '/energia'
      fullPath: '/energia'
      preLoaderRoute: typeof EnergiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flota': {
      id: '/flota'
      path: '/flota'
      fullPath: '/flota'
      preLoaderRoute: typeof FlotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum': {
      id: '/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof QuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salud': {
      id: '/salud'
      path: '/salud'
      fullPath: '/salud'
      preLoaderRoute: typeof SaludRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector': {
      id: '/sector'
      path: '/sector'
      fullPath: '/sector'
      preLoaderRoute: typeof SectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AhoraRoute: AhoraRoute,
  BenchRoute: BenchRoute,
  BiologiaRoute: BiologiaRoute,
  DoctrineRoute: DoctrineRoute,
  EnergiaRoute: EnergiaRoute,
  FlotaRoute: FlotaRoute,
  GridRoute: GridRoute,
  IaRoute: IaRoute,
  PlanRoute: PlanRoute,
  QuantumRoute: QuantumRoute,
  ResearchRoute: ResearchRoute,
  RoadmapRoute: RoadmapRoute,
  SaludRoute: SaludRoute,
  SectorRoute: SectorRoute,
  SpaceRoute: SpaceRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
